import "./globals.css";
import ClientComponent from "@/components/ClientComponent";
import ToasterProvider from "@/provider/ToasterProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Expozone",
  description: "Generated by create next app",
  icons: "/assets/brand-logo.svg",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientComponent>
          <ToasterProvider />
        </ClientComponent>
        <div>{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
