import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Expozone",
  description: "Generated by create next app",
  icons: "/assets/brand-logo.svg",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
